### PR TITLE
Add API key flow, language simplifications and some minor changes

### PR DESCRIPTION
**Pull request by subatoi**
This PR adds the API key flow information from the testing environment, and includes some improvements/simplifications to language (nothing which should drastically alter the user experience and all of which has been gleaned from the recent user research) 

This can merged into `master` in advance of deployment tomorrow 

This needs to be reviewed by @danmitchell- at a minimum; anyone else who has time, would be great.

### CODE REVIEW

**Comment by danmitchell-** [comment]
No issues from me @bahmady  👍

**Review by arnau — APPROVED** [review]

**Comment by michaelabenyohai** [comment]
@bahmady we are currently reviewing when we will deploy API keys so let's hold off merging this for now.

**Comment by bahmady** [comment]
OK @michaelabenyohai someone else will probably need to merge this and resolve any possible conflicts but as far as I'm concerned it should be ready

**Review by michaelabenyohai — APPROVED** [review]
Wondering if we should open a separate PR (I can do this tomorrow) to add the authorization header to all the existing curl examples. Thoughts @arnau?

**Pull request merged**
